### ISSUE TITLE
Audacity flatpak does not work in linuxmint 18.2

### ISSUE THREAD

**Issue by Lvaskz** [flathub/org.audacityteam.Audacity#1]
hi, audacity flatpak is already install in linuxmint 18.2 but not run.
I use the flatpak commands to run and it does not work.

**Comment by TingPing** [comment]
Any error output?

**Comment by Lvaskz** [comment]
hi, in some momento during this day i gonna send a video showing what is happening

**Comment by Lvaskz** [comment]
flatpak run org.audacityteam.Audacity/x86_64/stable
audacity: error while loading shared libraries: libFLAC++.so.6: cannot open
shared object file: No such file or directory

2017-09-18 17:00 GMT-06:00 Luis Vasquez <rugamagama@gmail.com>:

**Comment by TingPing** [comment]
This is also being discussed at flathub/flathub#96 and will be resolved soon.

**Comment by Lvaskz** [comment]
hi, know is working. thanks
