### ISSUE TITLE
Audacity does not start

### ISSUE THREAD

**Issue by Gandalf888** [flathub/org.audacityteam.Audacity#12]
After running audacity, this error appears:
```
Gtk-Message: Failed to load module "unity-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
11:04:14: Debug: Failed to connect to session manager: Could not open network socket
ALSA lib conf.c:3942:(snd_config_update_r) Cannot access file /etc/alsa-pulse.conf
audacity: src/hostapi/alsa/pa_linux_alsa.c:1454: BuildDeviceList: Assertion `devIdx < numDeviceNames' failed.
```

After which the application will be closed (only the logo is shown). Audacity installed from the repository works correctly.

**Additional information:**

Operating system:

LSB Version:    n/a
Distributor ID: openSUSE
Description:    openSUSE Tumbleweed
Release:        20180807
Codename:       n/a

**Flatpak version:**
Flatpak 0.11.8.3

**CPU**
x86_64

**Comment by jurf** [comment]
Hm, I cannot reproduce this, but it looks similar to flathub/com.valvesoftware.Steam#102.

Can you try running Audacity with `flatpak run --env=ALSA_CONFIG_PATH= org.audacityteam.Audacity` and see if it helps?

**Comment by Gandalf888** [comment]
Yes, after running this command, the program starts and works correctly.

**Comment by jurf** [comment]
Easy fix then.

**Comment by jurf** [comment]
Update should be ready for download in a little while.
