### ISSUE TITLE
Still unable to open m4a due to missing ffmpeg

### ISSUE THREAD

**Issue by millerthegorilla** [flathub/org.audacityteam.Audacity#129]
Hi,   I am unable to use the flatpak audacity to open/edit m4a files.  Audacity complains that the FFMPeg Library cannot be loaded, but Audacity runs in a sandbox, so ffmpeg needs to either be included or a separate plugin, sharing the same sandbox, needs to be created...

**Comment by millerthegorilla** [comment]
I just installed Clementine, the audio player and it has no issues opening m4a files, perhaps because it includes ```org.freedesktop.Platform.openh264```   but would this allow the editing of files, or is there a separate ffmpeg package that needs to be included in the sandbox?

**Comment by hfiguiere** [comment]
I just opened a m4a file in Audacity. No problem.

**Comment by millerthegorilla** [comment]
Hi, thanks for that, I was using the fedora version which is waayyyy out of date.  It all works fine now.
