### ISSUE TITLE
Play head problem with flatpak 3.4.1

### ISSUE THREAD

**Issue by bertradio** [flathub/org.audacityteam.Audacity#136]
I am running the flatpak edition of Audacity on a Chromebook under Crostini. I had version 3.4.0 which was working properly. Today I updated it to version 3.4.1 and have a display problem with the play head. In default mode, it does not move reliably with the audio. It seems to move in spurts, sometimes not moving at all. But if I select “pin head” everything behaves as it should. 3.4.0 did not have this problem.

**Comment by bertradio** [comment]
Found the issue, It has to do with Wayland. If Wayland is enabled for Audacity in flatpak, the play head does not move. If only X11 is enabled, the GUI is uglier, but it behaves properly. This can all be set in Flatseal.

**Comment by hfiguiere** [comment]
Wayland isn't enabled in this package.
