### ISSUE TITLE
It seems like the .desktop file causes problems with window managers identifying the window

### ISSUE THREAD

**Issue by ell1e** [flathub/org.audacityteam.Audacity#143]
It seems like the flatpak's current .desktop file causes problems with window managers identifying the window:

[Steps to reproduce for the Phosh window manager are in a comment below.](https://github.com/flathub/org.audacityteam.Audacity/issues/143#issuecomment-1872322486)

In many window managers like Phosh or gnome-shell and I believe also KDE, that show an app icon to identify the running app, clicking that icon is supposed to auto-identify any of the already opened app windows to focus on them. But when the desktop file doesn't allow the WM/compositor to find the associated windows, it'll rather launch the app again (which will be prevented often by multi instance preventing code, and as a result turn the icon strangely entirely useless for a baffled user).

This "useless icon" phenomenon is what Audacity is currently showing at least with the Phosh wayland desktop I'm using.

Apparently, for this to work under wayland [the desktop file needs to be named after the app id](https://gitlab.alpinelinux.org/alpine/aports/-/issues/15619#note_365992) that was [specified in the desktop file](https://github.com/flathub/org.audacityteam.Audacity/blob/c924c40308b75ee3c6ee08ece3d357d43380ddee/org.audacityteam.Audacity.yaml#L1), and it seems like that would mean a file name of `org.audacityteam.Audacity.desktop` and [not `audacity.desktop`](https://github.com/flathub/org.audacityteam.Audacity/blob/c924c40308b75ee3c6ee08ece3d357d43380ddee/org.audacityteam.Audacity.yaml#L8).

**Comment by hfiguiere** [comment]
works fine here. I run GNOME.

Are you sure you are running the flathub provided version?

**Comment by ell1e** [comment]
It works with gnome-shell, that's correct, but it doesn't with [Phosh](https://gitlab.gnome.org/World/Phosh/phosh).

Steps to reproduce are:

1. Have Phosh desktop installed on some device (it's e.g. available on Fedora for x64 machines as a regular desktop, other than that it's commonly used on the Librem 5 and PinePhone and PinePhone Pro devices that are on a technical level a lot like a Raspberry PI but in a phone form factor) and launch Phosh desktop session

2. Install audacity from flathub, by first making sure flathub remote exists and then: `sudo flatpak install flathub org.audacityteam.Audacity`

3. If the Audacity icon didn't appear in the Phosh app drawer (the one reachable by dragging up the bottom bar)  which occasionally seems to be an issue when installing something new that it doesn't appear, then reboot the Phone as an easy workaround.

4. Launch Audacity via the Phosh app drawer by pressing the Audacity icon in the icon list

5. Wait until Audacity main window came up. You may need to confirm or dismiss various popups or wait through some loading splash screens.

6. Now go back to the phosh app drawer, and launch something else, e.g. GNOME Text Editor (gedit) and wait until it shows up and is brought to the foreground.

7. Now go back to the Phosh app drawer a third time and press the Audacity icon again.

Expected behavior: Audacity window is brought to foreground and set the focus to.

Actual behavior: You're still seeing the GNOME Text editor (gedit) window, or whatever else you opened, and switching to Audacity doesn't work.

Almost no other apps are affected at this point, but for those who were it always was some problem with the desktop file.

**Comment by ell1e** [comment]
> And this is the case. Has always been as it's a requirement.

Well it seems like in gnome-shell it tends to work even if the desktop file is renamed, for some reason. And the line I linked from the Audacity build scripts indicates t hat the file name is `audacity.desktop` and not `org.audacityteam.Audacity.desktop` which could be related to this problem with Phosh.

However, I only recently learned Audacity actually runs via XWayland and not directly via Wayland for plugin compatibility. (As a side note, I hope plugin support is expected to be available via some Wayland API at some point, isn't XWayland basically being more and more pushed into deprecation by all distributions? Seems like a dead end that will be reached in a few years, and since plugins will also take a few years to be rewritten once a different non-X11 approach exists, solving that seems like an issue that maybe is actually somewhat pressing.) I don't know what this means exactly for this bug or how exactly to fix it then.

**Comment by hfiguiere** [comment]
> And the line I linked from the Audacity build scripts indicates that the file name is `audacity.desktop` and not `org.audacityteam.Audacity.desktop`

This is false.

**Comment by ell1e** [comment]
Ah, I see. Strange. Then whatever I wrote about what causes this with Phosh is likely incorrect. Nevertheless, it does remain an issue for some reason. I suppose it could be a Phosh bug, I really wouldn't know, but so far for [a lot of other apps it has been fixable which has been an ongoing effort in this "Alpine" Linux distribution ticket](https://gitlab.alpinelinux.org/alpine/aports/-/issues/15619).

**Comment by Sertonix** [comment]
@ell1e Could you run `xprop -name 'Audacity' WM_CLASS` after opening audacity and send the output?

**Comment by ell1e** [comment]
Sure! it says:
```
$ xprop -name 'Audacity' WM_CLASS
WM_CLASS(STRING) = "audacity.bin", "Audacity"
$
```

**Comment by Sertonix** [comment]
I didn't know that the audacity flatpak runs under xwayland. Then this is a phosh issue.

@ell1e I think this issue is invalid then.

**Comment by ell1e** [comment]
Okay! My apologies for the bug tracker noise to the audacity devs, I'm closing this hten.
