### ISSUE TITLE
Enable the "Fallback to X11 windowing system" and "Wayland windowing system" options

### ISSUE THREAD

**Issue by ell1e** [flathub/org.audacityteam.Audacity#145]
Audacity should be using the option for packaging the flathub release that's equivalent to [flatseal's "Fallback to X11 windowing system" option that only allows using X11 if Wayland is unavailable](https://github.com/tchx84/Flatseal/issues/619#issuecomment-1841069915) and also be using the Wayland windowing option.

This would fix two things: 1. The UI is blurry and ugly, which isn't fixed by just enabling the Wayland access alone since Audacity right now seems to always use X11 if ever possible even if there's Wayland access which makes it use the way inferior XWayland, 2. it improves security by cutting off X11 access unless it's actually needed as the only option.

**Comment by hfiguiere** [comment]
Audio plugins UI don't work with wayland.

**Comment by lucasmz-dev** [comment]
@hfiguiere It isn't this thing right?

![image](https://github.com/user-attachments/assets/961dce52-4ebc-4e32-aeef-5c6f817645de)

**Comment by hfiguiere** [comment]
no
