### ISSUE TITLE
Improve appdata  (screenshots, urls, release_version, ...)

### ISSUE THREAD

**Issue by jgarciao** [flathub/org.audacityteam.Audacity#17]
In order to have more information shown at https://flathub.org/apps/details/org.audacityteam.Audacity the appdata for this app could be improved:
- screenshots (there are some in their website)
- urls: [donation](https://www.audacityteam.org/donate/), [help](https://www.audacityteam.org/help/)
- release info
- license
- developer name

**Comment by jurf** [comment]
This would be better opened upstream though.

**Comment by jgarciao** [comment]
The informatin is actually [there](https://github.com/audacity/audacity/blob/master/help/audacity.appdata.xml). It might be a problem in the website sync

I've opened this issue to take a look https://github.com/flathub/linux-store-frontend/issues/140
