### ISSUE TITLE
Audacity is not translated to spanish

### ISSUE THREAD

**Issue by Lvaskz** [flathub/org.audacityteam.Audacity#18]
I updated to 2.30 but in preferences of app,Spanish language is missing

**Comment by jurf** [comment]
Try running a `flatpak update` manually.

**Comment by Lvaskz** [comment]
I did it, but the spanish language still missing

**Comment by jurf** [comment]
Do other languages work? If yeah, then this probably won’t be a Flatpak problem.

Can you please post the output of `$ echo $LANG`?

**Comment by Lvaskz** [comment]
Yea, other idioms work, Spanish is missing. I can change any other language and it works.
About the command, just let me some time I am not in my personal computer.

**Comment by Lvaskz** [comment]
I tried with audacity. Appimage Spanish language comes.

**Comment by Lvaskz** [comment]
lvaskz@lvaskz-Inspiron-3442:~$  echo $LANG
es_CR.UTF-8
lvaskz@lvaskz-Inspiron-3442:~$ 
This is the output

**Comment by Lvaskz** [comment]
![captura de pantalla de 2018-11-20 06-53-51](https://user-images.githubusercontent.com/29207169/48774916-1dd96680-ec91-11e8-9d1b-f947a006f4c7.png)

**Comment by Lvaskz** [comment]
OK, but I will soon.

**Comment by Lvaskz** [comment]
![vlcsnap-2018-11-21-20h05m59s793](https://user-images.githubusercontent.com/29207169/48877486-0e5d3900-edc9-11e8-93ff-7b7a3602cd28.png)

**Comment by jurf** [comment]
That’s just strange… does the same thing happen if you run it with `flatpak run org.audacityteam.Audacity`?

**Comment by Lvaskz** [comment]
Yes with the command is the same.

~$ flatpak run org.audacityteam.Audacity
ALSA lib ../../src/confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib ../../src/conf.c:4555:(_snd_config_evaluate) function snd_func_card_driver returned error: No existe el fichero o el directorio
ALSA lib ../../src/confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib ../../src/conf.c:4555:(_snd_config_evaluate) function snd_func_concat returned error: No existe el fichero o el directorio
ALSA lib ../../src/confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib ../../src/conf.c:4555:(_snd_config_evaluate) function snd_func_refer returned error: No existe el fichero o el directorio
ALSA lib ../../src/conf.c:5034:(snd_config_expand) Evaluate error: No existe el fichero o el directorio
ALSA lib ../../../src/pcm/pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM sysdefault
ALSA lib ../../src/confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib ../../src/conf.c:4555:(_snd_config_evaluate) function snd_func_card_driver returned error: No existe el fichero o el directorio
ALSA lib ../../src/confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib ../../src/conf.c:4555:(_snd_config_evaluate) function snd_func_concat returned error: No existe el fichero o el directorio
ALSA lib ../../src/confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib ../../src/conf.c:4555:(_snd_config_evaluate) function snd_func_refer returned error: No existe el fichero o el directorio
ALSA lib ../../src/conf.c:5034:(snd_config_expand) Evaluate error: No existe el fichero o el directorio
ALSA lib ../../../src/pcm/pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM sysdefault
ALSA lib ../../../src/pcm/pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.front
ALSA lib ../../../src/pcm/pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib ../../../src/pcm/pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib ../../../src/pcm/pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib ../../../src/pcm/pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib ../../../src/pcm/pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib ../../../src/pcm/pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround40
ALSA lib ../../../src/pcm/pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround41
ALSA lib ../../../src/pcm/pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround50
ALSA lib ../../../src/pcm/pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround51
ALSA lib ../../../src/pcm/pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround71
ALSA lib ../../../src/pcm/pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib ../../../src/pcm/pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib ../../../src/pcm/pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib ../../../src/pcm/pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib ../../../src/pcm/pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib ../../../src/pcm/pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib ../../../src/pcm/pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib ../../../src/pcm/pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib ../../../src/pcm/pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib ../../src/confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib ../../src/conf.c:4555:(_snd_config_evaluate) function snd_func_card_driver returned error: No existe el fichero o el directorio
ALSA lib ../../src/confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib ../../src/conf.c:4555:(_snd_config_evaluate) function snd_func_concat returned error: No existe el fichero o el directorio
ALSA lib ../../src/confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib ../../src/conf.c:4555:(_snd_config_evaluate) function snd_func_refer returned error: No existe el fichero o el directorio
ALSA lib ../../src/conf.c:5034:(snd_config_expand) Evaluate error: No existe el fichero o el directorio
ALSA lib ../../../src/pcm/pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM dmix
ALSA lib ../../../src/seq/seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: No existe el fichero o el directorio
Expression 'stream->capture.pcm' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 4594
13:39:43: Debug: ScreenToClient cannot work when toplevel window is not shown
13:39:43: Debug: ScreenToClient cannot work when toplevel window is not shown
13:39:43: Debug: ScreenToClient cannot work when toplevel window is not shown
13:39:43: Debug: ScreenToClient cannot work when toplevel window is not shown
13:39:43: Debug: ScreenToClient cannot work when toplevel window is not shown
13:39:43: Debug: ScreenToClient cannot work when toplevel window is not shown
13:39:43: Debug: ScreenToClient cannot work when toplevel window is not shown
13:39:43: Debug: ScreenToClient cannot work when toplevel window is not shown
13:39:43: Debug: ScreenToClient cannot work when toplevel window is not shown
13:39:44: Debug: ScreenToClient cannot work when toplevel window is not shown
13:39:44: Debug: ScreenToClient cannot work when toplevel window is not shown
13:39:44: Debug: ScreenToClient cannot work when toplevel window is not shown
13:39:44: Debug: ScreenToClient cannot work when toplevel window is not shown
13:39:44: Debug: ScreenToClient cannot work when toplevel window is not shown
13:39:44: Debug: ScreenToClient cannot work when toplevel window is not shown
13:39:44: Debug: ScreenToClient cannot work when toplevel window is not shown
13:39:44: Debug: ScreenToClient cannot work when toplevel window is not shown
13:39:44: Debug: ScreenToClient cannot work when toplevel window is not shown
13:39:44: Debug: ScreenToClient cannot work when toplevel window is not shown
13:39:44: Debug: ScreenToClient cannot work when toplevel window is not shown
13:39:44: Debug: ScreenToClient cannot work when toplevel window is not shown
13:39:44: Debug: ScreenToClient cannot work when toplevel window is not shown
13:39:44: Debug: ScreenToClient cannot work when toplevel window is not shown
13:39:44: Debug: ScreenToClient cannot work when toplevel window is not shown
13:39:44: Debug: ScreenToClient cannot work when toplevel window is not shown
13:39:44: Debug: ScreenToClient cannot work when toplevel window is not shown
13:39:44: Debug: ScreenToClient cannot work when toplevel window is not shown
13:39:44: Debug: ClientToScreen cannot work when toplevel window is not shown
13:39:44: Debug: ClientToScreen cannot work when toplevel window is not shown
13:39:44: Debug: ClientToScreen cannot work when toplevel window is not shown
13:39:44: Debug: ClientToScreen cannot work when toplevel window is not shown
13:39:44: Debug: ClientToScreen cannot work when toplevel window is not shown
13:39:44: Debug: ClientToScreen cannot work when toplevel window is not shown
13:39:44: Debug: ClientToScreen cannot work when toplevel window is not shown
13:39:44: Debug: ClientToScreen cannot work when toplevel window is not shown
13:39:44: Debug: ClientToScreen cannot work when toplevel window is not shown
13:39:44: Debug: Unrecognized accel key 'backspace', accel string ignored.
13:39:44: Debug: Unrecognized accel key 'backspace', accel string ignored.
13:39:44: Debug: Unrecognized accel key 'numpad_enter', accel string ignored.
13:39:44: Debug: Unrecognized accel key 'numpad_enter', accel string ignored.
13:39:44: Debug: ClientToScreen cannot work when toplevel window is not shown
13:39:44: Debug: ClientToScreen cannot work when toplevel window is not shown
13:39:44: Debug: ClientToScreen cannot work when toplevel window is not shown
13:39:44: Debug: ClientToScreen cannot work when toplevel window is not shown
13:39:44: Debug: ClientToScreen cannot work when toplevel window is not shown
13:39:44: Debug: ClientToScreen cannot work when toplevel window is not shown
13:39:44: Debug: ClientToScreen cannot work when toplevel window is not shown
13:39:44: Debug: ClientToScreen cannot work when toplevel window is not shown
13:39:44: Debug: ClientToScreen cannot work when toplevel window is not shown
13:39:44: Debug: ClientToScreen cannot work when toplevel window is not shown
13:39:44: Debug: ClientToScreen cannot work when toplevel window is not shown

**Comment by Lvaskz** [comment]
![captura de pantalla de 2018-11-22 13-41-40](https://user-images.githubusercontent.com/29207169/48920097-76a92a80-ee5c-11e8-8226-ff3ac96ec2cd.png)

**Comment by Lvaskz** [comment]
Any progress ?


Atte Luis Vasquez Rugama

**Comment by jurf** [comment]
Could you try running `flatpak info org.audacityteam.Audacity.Locale` and posting the output?

**Comment by Lvaskz** [comment]
ok I will soom.

**Comment by Lvaskz** [comment]
lvaskz@lvaskz-Inspiron-3442:~$ flatpak info org.audacityteam.Audacity.Locale 
Referencia: runtime/org.audacityteam.Audacity.Locale/x86_64/stable
ID: org.audacityteam.Audacity.Locale
Arquitectura: x86_64
Rama: stable
Origen: flathub
Collection ID: org.flathub.Stable
Date: 2018-10-01 09:50:08 +0000
Subject: Cleanout chrpath (bbb36cb4)
Commit: 8ca8317029af00e4d99b9362d5709cbe3bfdde82772e4c46b5ebbfba5ca373c1
Parent: bdd761c6ab4c4c57af160ed44b03e857cd2ac1f1dc2f56e9d6b7935532d42651
Localización: /var/lib/flatpak/runtime/org.audacityteam.Audacity.Locale/x86_64/stable/8ca8317029af00e4d99b9362d5709cbe3bfdde82772e4c46b5ebbfba5ca373c1
Tamaño de la instalación: 13,0 MB

**Comment by jurf** [comment]
Oh, okay, looks like the locale wasn’t even installed…

**Comment by Lvaskz** [comment]
my app is still in English, I must do something ?

**Comment by Lvaskz** [comment]
Hi, I reinstalled the app, but It still in english.

**Comment by jurf** [comment]
Maybe try running `flatpak install --reinstall flathub org.audacityteam.Audacity.Locale`?

**Comment by Lvaskz** [comment]
ok I will. By the way I installed audacity 2.3.1, same issue; all language
except spanish.

**Comment by Lvaskz** [comment]
> Maybe try running `flatpak install --reinstall flathub org.audacityteam.Audacity.Locale`

Nop, same problem.

**Comment by Lvaskz** [comment]
snap version has same problem.....weird

**Comment by jurf** [comment]
Are you sure Audacity is even translated to `es_CR`?

**Comment by Lvaskz** [comment]
Previous versions of audacity in flatpak were translated into Spanish CR, after version 2.3.0 the issue appeared

**Comment by Lvaskz** [comment]
I downloaded a deb package. It has the same issue, so I think is not an issue about flatpak package, so I will close. And I will report to audacity issues Thanks

**Comment by benediktg** [comment]
I had the sme problem with the Flatpak edition and German and it worked after I set `Language=` to `de` in `~/.audacity-data/audacity.cfg`. Spanish is `es`.
https://manual.audacityteam.org/man/languages.html
