### ISSUE TITLE
Audacity creates a folder in $HOME

### ISSUE THREAD

**Issue by jurf** [flathub/org.audacityteam.Audacity#20]
Just found `.audacity-data` in my `~/`. I guess we should add this to persist, but that would mean users would ‘lose’ their config files. Maybe a migration script? But that sucks.

**Comment by TingPing** [comment]
perist cant work with host access. You need to patch Audacity to respect XDG (and migrate) and throw that patch upstream and hope they care.

**Comment by jurf** [comment]
Glorious.

**Comment by hfiguiere** [comment]
My experience with upstream patch isn't good. One of the patches for building `suil` correctly to support LV2 has been rotting for month.

**Comment by TheEvilSkeleton** [comment]
> perist cant work with host access. You need to patch Audacity to respect XDG (and migrate) and throw that patch upstream and hope they care.

Tenacity recently added support for XDG, see https://github.com/tenacityteam/tenacity/pull/378. Perhaps we could use it (and of course do the migration thing)?

**Comment by TingPing** [comment]
> Tenacity recently added support for XDG, see tenacityteam/tenacity#378. Perhaps we could use it (and of course do the migration thing)?

Feel free to package Tenacity but its inappropriate to use migration to another fork when the project remains active.

**Comment by TheEvilSkeleton** [comment]
Way ahead of you :') https://github.com/flathub/flathub/pull/2444

**Comment by hfiguiere** [comment]
Closing this, it's an upstream issue.
