### ISSUE TITLE
Audacity can't open in Endless OS

### ISSUE THREAD

**Issue by buga123** [flathub/org.audacityteam.Audacity#21]
Hello, I have a problem with the app,

I use Endless OS 3.4.8. Acer Aspire 3 laptop.

I download it in the App Center of Endless os, when I wanna to open it, the app doesn't do anything.

I use the terminal to open it with:  flatpak run org.audacityteam.Audacity
after it say: audacity: error while loading shared libraries: libmp3lame.so.0: cannot open shared object file: No such file or directory

Please help me to fix it.

**Comment by jurf** [comment]
That’s just weird…

Are you sure you are using the Flathub one? Could you please post the output of:

```
❯ flatpak list -d | grep audacity
```

**Comment by buga123** [comment]
org.audacityteam.Audacity/x86_64/stable	flathub	3085f853aa0f	-	36.0 MBsystem,current
org.audacityteam.Audacity.Codecs/x86_64/stable	flathub	6ebdca08107c	-	3.3 MB	system,runtime

**Comment by jurf** [comment]
Hm, could you try a `flatpak update`, just in case?

**Comment by buga123** [comment]
I think it's not a good thing: Looking for updates...
flatpak update: Warning: No xa.metadata in commit 38efc5893c8b90b2658ed2889bcbdb4d65b2436fb8dcf70feba32932caaeda3f ref app/com.endlessm.translation/x86_64/eos3

**Comment by buga123** [comment]
After the update it doesnt work too.

**Comment by jurf** [comment]
Is that the whole output?

**Comment by buga123** [comment]
flatpak update
Looking for updates...
flatpak update: Warning: No xa.metadata in commit 38efc5893c8b90b2658ed2889bcbdb4d65b2436fb8dcf70feba32932caaeda3f ref app/com.endlessm.translation/x86_64/eos3
Installing in system:
com.endlessm.CompanionAppService.Locale/x86_64/stable eos-sdk 79d0695932c8
Updating in system:
com.endlessm.translation/x86_64/eos3                    eos-apps 38efc5893c8b
org.freedesktop.Platform.Compat32/x86_64/1.6            flathub  e7af5327f4ae
org.freedesktop.Platform/x86_64/1.6                     flathub  8b967508e3e7
org.freedesktop.Platform.Locale/x86_64/1.6              flathub  2d52b9c7af8c
org.libreoffice.LibreOffice.Locale/x86_64/stable        flathub  9c90f44aed9c
com.google.Chrome/x86_64/eos3                           eos-apps f05f301c65d1
com.endlessm.apps.Platform.Locale/x86_64/5              eos-sdk  3439ef327335
com.endlessm.okezone.id/x86_64/eos3                     eos-apps 6d5286c4def9
com.endlessm.okezone.id.Content/x86_64/eos3             eos-apps 4ac3c85ff42e
com.endlessm.kapan_lagi.id/x86_64/eos3                  eos-apps 8bd8928eac3c
com.endlessm.kapan_lagi.id.Content/x86_64/eos3          eos-apps 92ea2b82cb3f
org.freedesktop.Platform.Icontheme.EndlessOS/x86_64/1.0 eos-sdk  1f68bf2ac902
org.freedesktop.Platform/x86_64/18.08                   flathub  ce0ac7de97e7
org.freedesktop.Platform.Locale/x86_64/18.08            flathub  be0744bd1e50
org.freedesktop.Platform.Compat.i386/x86_64/18.08       flathub  2827ef887617
org.gnome.Platform/x86_64/3.24                          flathub  72388eb9f5ab
org.gnome.Platform.Locale/x86_64/3.24                   flathub  6677c064658c
org.gnome.Platform/x86_64/3.26                          flathub  206dc8b94b67
org.gnome.Platform.Locale/x86_64/3.26                   flathub  e730b2c2e992
org.gnome.Platform/x86_64/3.28                          flathub  bc98106ca173
org.gnome.Platform.Locale/x86_64/3.28                   flathub  2823e3d81b74
org.pitivi.Pitivi.Codecs/x86_64/stable                  flathub  53cd99c9811e
org.pitivi.Pitivi.Locale/x86_64/stable                  flathub  3254c2666b41
org.gnome.Weather/x86_64/stable                         flathub  75b743eb966b
org.gnome.Weather.Locale/x86_64/stable                  flathub  3c1cec6f5302
org.gnome.Platform/x86_64/3.30                          flathub  124b2831f375
org.freedesktop.Platform.VAAPI.Intel/x86_64/18.08       flathub  041424177ff8
org.freedesktop.Platform.html5-codecs/x86_64/18.08      flathub  5a50ab29ed3d
org.gnome.Gnote.Locale/x86_64/stable                    flathub  cd5865b2a6ba
org.kde.Platform/x86_64/5.11                            flathub  ad8db7240a16
org.kde.Platform.Locale/x86_64/5.11                     flathub  e764eeecd976
org.kde.Platform/x86_64/5.9                             flathub  950ba90bd04c
org.kde.Platform.Locale/x86_64/5.9                      flathub  38558decd574
Is this ok [y/n]: ^C

**Comment by jurf** [comment]
Well, you have the confirm it, you are quite badly out of date.

**Comment by buga123** [comment]
Well?

**Comment by jurf** [comment]
What well? You didn’t update your system, you have to answer yes to the prompt. :grinning:

Or, alternatively, run `flatpak update -y`.

**Comment by hfiguiere** [comment]
Not sue there is anything to do here.
