### ISSUE TITLE
Audacity crashes after click on the File/Open Menu

### ISSUE THREAD

**Issue by ThyQueen** [flathub/org.audacityteam.Audacity#23]
Laptop: MSI GP62M 7REX Leopard Pro
System: Linux MInt 18.3 Cinnamon 64 bit

It has worked flawlessly for about a month and now suddenly it crashes if I attempt to open any file. It does not crash if I select the file first and right mouse click (open with Audacity).

The automatic error log in Temporary files was empty so I manually copied and paste the report:

[audacity-configs.txt](https://github.com/flathub/org.audacityteam.Audacity/files/2767959/audacity-configs.txt)

**Comment by jurf** [comment]
Hey, just a quick note, that file is massive, next time please either paste the whole file here as I have, or use something like Pastebin.

**Comment by ThyQueen** [comment]
Ok.Thanks for letting me know.

**Comment by jurf** [comment]
Actually, I just noticed that those were multiple files? Yeah, you can just zip them and upload them like so: [audacity-configs.zip](https://github.com/flathub/org.audacityteam.Audacity/files/2767950/audacity-configs.zip)

**Comment by jurf** [comment]
Anyway, looked through them, I didn’t find anything interesting. The log is almost empty. Could you try running Audacity through the command line with `flatpak run org.audacityteam.Audacity`?

**Comment by ThyQueen** [comment]
Juraj, I did what you said and I have the output here:
https://pastebin.com/fuHckWtA

In the meantime, I'm using the other version (non flatpak 2.1.2) for my
music which works perfectly fine!

**Comment by TingPing** [comment]
This was a bug in the runtime that should be fixed by the latest update.
