### ISSUE TITLE
extract audio from video

### ISSUE THREAD

**Issue by FastOSlinux** [flathub/org.audacityteam.Audacity#24]
I can not extract audio from a video (mkv h264)

![2019-01-28_16-30](https://user-images.githubusercontent.com/17401812/51857732-20ec7500-231a-11e9-9dd6-4a6c8215d2a1.png)

![2019-01-28_16-35](https://user-images.githubusercontent.com/17401812/51857961-b6880480-231a-11e9-9946-4fde873027f5.png)

flatpak list
Ref                                                    Opções      
org.freedesktop.Platform.Compat.i386/x86_64/18.08      user,runtime  
com.discordapp.Discord/x86_64/stable                   system,current
com.github.wwmm.pulseeffects/x86_64/stable             system,current
com.moonlight_stream.Moonlight/x86_64/stable           system,current
com.obsproject.Studio/x86_64/stable                    system,current
com.spotify.Client/x86_64/stable                       system,current
com.uploadedlobster.peek/x86_64/stable                 system,current
com.valvesoftware.Steam/x86_64/stable                  system,current
com.wps.Office/x86_64/stable                           system,current
net.pcsx2.PCSX2/i386/stable                            system,current
org.audacityteam.Audacity/x86_64/stable                system,current
org.gimp.GIMP/x86_64/stable                            system,current
org.gnome.Boxes/x86_64/stable                          system,current
org.gnome.font-viewer/x86_64/stable                    system,current
org.libreoffice.LibreOffice/x86_64/stable              system,current
org.mozilla.FirefoxNightly/x86_64/master               system,current
org.ppsspp.PPSSPP/x86_64/stable                        system,current
org.qbittorrent.qBittorrent/x86_64/stable              system,current
org.telegram.desktop/x86_64/stable                     system,current
org.videolan.VLC/x86_64/stable                         system,current
org.audacityteam.Audacity.Codecs/x86_64/stable         system,runtime
org.freedesktop.Platform.Compat.i386/x86_64/18.08      system,runtime
org.freedesktop.Platform.GL.nvidia-390-59/i386/1.4     system,runtime
org.freedesktop.Platform.GL.nvidia-390-59/x86_64/1.4   system,runtime
org.freedesktop.Platform.GL.nvidia-396-54/x86_64/1.4   system,runtime
org.freedesktop.Platform.GL.nvidia-410-66/i386/1.4     system,runtime
org.freedesktop.Platform.GL.nvidia-410-66/x86_64/1.4   system,runtime
org.freedesktop.Platform.GL.nvidia-410-73/i386/1.4     system,runtime
org.freedesktop.Platform.GL.nvidia-410-73/x86_64/1.4   system,runtime
org.freedesktop.Platform.GL.nvidia-410-78/i386/1.4     system,runtime
org.freedesktop.Platform.GL.nvidia-410-78/x86_64/1.4   system,runtime
org.freedesktop.Platform.GL.nvidia-415-18/i386/1.4     system,runtime
org.freedesktop.Platform.GL.nvidia-415-18/x86_64/1.4   system,runtime
org.freedesktop.Platform.GL.nvidia-415-25/i386/1.4     system,runtime
org.freedesktop.Platform.GL.nvidia-415-25/x86_64/1.4   system,runtime
org.freedesktop.Platform.GL.nvidia-415-27/i386/1.4     system,runtime
org.freedesktop.Platform.GL.nvidia-415-27/x86_64/1.4   system,runtime
org.freedesktop.Platform.GL32.nvidia-410-73/x86_64/1.4 system,runtime
org.freedesktop.Platform.GL32.nvidia-410-78/x86_64/1.4 system,runtime
org.freedesktop.Platform.GL32.nvidia-415-18/x86_64/1.4 system,runtime
org.freedesktop.Platform.GL32.nvidia-415-25/x86_64/1.4 system,runtime
org.freedesktop.Platform.GL32.nvidia-415-27/x86_64/1.4 system,runtime
org.freedesktop.Platform.Icontheme.Adwaita/x86_64/1.0  system,runtime
org.freedesktop.Platform.ffmpeg/x86_64/1.6             system,runtime
org.freedesktop.Platform.html5-codecs/i386/18.08       system,runtime
org.freedesktop.Platform.html5-codecs/x86_64/18.08     system,runtime
org.freedesktop.Platform/i386/18.08                    system,runtime
org.freedesktop.Platform/x86_64/1.6                    system,runtime
org.freedesktop.Platform/x86_64/18.08                  system,runtime
org.gnome.Platform/x86_64/3.26                         system,runtime
org.gnome.Platform/x86_64/3.28                         system,runtime
org.gnome.Platform/x86_64/3.30                         system,runtime
org.gtk.Gtk3theme.Adapta/x86_64/3.22                   system,runtime
org.gtk.Gtk3theme.Arc-Dark/x86_64/3.22                 system,runtime
org.gtk.Gtk3theme.Arc/x86_64/3.22                      system,runtime
org.kde.KStyle.Adwaita/x86_64/5.12                     system,runtime
org.kde.Platform/x86_64/5.12                           system,runtime

**Comment by DanMan** [comment]
The real problem here is that Audacity can't use ffmpeg, even if it's installed on the system. A solution for that would be good.

**Comment by antistress** [comment]
Indeed, I have the same problem with a VP9+Opus in WebM video dowloaded from YouTube
[Audacity manual says](https://manual.audacityteam.org/man/importing_audio.html) :

> Audacity does not natively support Opus format. If FFmpeg is installed, Audacity will attempt to use FFmpeg for importing Opus files. 

Very annoying

Thanks

**Comment by antistress** [comment]
Thanks !
