### ISSUE TITLE
help file is not included in audacity flatpak

### ISSUE THREAD

**Issue by Lvaskz** [flathub/org.audacityteam.Audacity#3]
Hi, the audacity help file is not included in the audacity flatpak. 
OS linuxmint 18.2 , cinnamon desktop
64 bit

**Comment by Lvaskz** [comment]
That would be nice, I guess

**Comment by jurf** [comment]
Had some discussion about this on IRC, I’ll add it as a .Doc extension, after that you can install it by enabling it in GNOME Software or what-have-you or using the CLI.

**Comment by mb291** [comment]
> Had some discussion about this on IRC, I’ll add it as a .Doc extension, after that you can install it by enabling it in GNOME Software or what-have-you or using the CLI.

Sorry - bu how can I install this ?

**Comment by hfiguiere** [comment]
I don't think this was every done.

**Comment by mb291** [comment]
> I don't think this was ever done.

OK - so where should I extract the manual (zip) then? I'm using the current flatpak (installed as user) --user.
I have root access also.

**Comment by jurf** [comment]
Yeah, I never got to it.

The ideal way to extract it would be with a PR to this repo. :P Modifying the flatpak repo directly, root or not, won’t help you in the long run.

**Comment by hfiguiere** [comment]
I have this implemented sort f #69 except that if I make the manual an extension it doesn't work...

**Comment by hfiguiere** [comment]
it's no longer provided by upstream.
