### ISSUE TITLE
Outdated - broken version

### ISSUE THREAD

**Issue by nadrolinux** [flathub/org.audacityteam.Audacity#30]
Hello,
On falthub there is an outdated Audacity version - 2.3.0. On official Audacity page there is an information that v2.3.0 is broken on Linux:
> Some distributions offer older Audacity 2.3.0 which is broken on Linux, or 2.0.6, 2.1.0 or 2.1.1 that were incorrectly built against too recent wxWidgets (3.0.x).  Audacity 2.3.2 may be built against wxWidgets 3.0.2 or 3.1.1.
Cheers,

**Comment by jurf** [comment]
Ah no, it is actually 2.3.1 (https://github.com/flathub/org.audacityteam.Audacity/commit/f7fa5a7e3b7e41ac153b621658fc01b721fd7113), but the Audacity guys didn’t update the AppData. However 2.3.2 was just released, so maybe it’s fixed there, I’ll do a quick PR.

**Comment by nadrolinux** [comment]
@jurf I would like to ask if any progress about update to v2.3.2?

**Comment by jurf** [comment]
It’s already updated to 2.3.2.

![obrázok](https://user-images.githubusercontent.com/7472425/59907542-9eb93600-940b-11e9-9e2b-530ed135b3c4.png)

**Comment by nadrolinux** [comment]
You're right. I had to manually uninstall and install Audacity to get v2.3.2. Update from v2.3.0 to v2.3.2 wasn't available in Gnome Software Manager.
