### ISSUE TITLE
Using GNOME Software didn't provide the french version : I had to install within a Terminal org.audacityteam.Audacity.Locale

### ISSUE THREAD

**Issue by antistress** [flathub/org.audacityteam.Audacity#33]
Hi,
I'm using Debian 64 bits Sid with GNOME X11 in french (flatpak version is 1.2.4-1 and gnome-software version is 3.30.6-5)
I've installed different applications from flathub using GNOME Software : some of them were translated in french, some of them don't.
For Audacity I had to open a Terminal and to manually install org.audacityteam.Audacity.Locale
Then Audacity was translated.

Thanks

**Comment by eszlari** [comment]
I think that's because gnome-software 3.30 didn't use libflatpak for installing yet, so you will need a newer version.

**Comment by antistress** [comment]
it seems to use gnome-software-plugin-flatpak which depends on libflatpak0
see https://packages.debian.org/sid/gnome-software

**Comment by TingPing** [comment]
Eitherway its a bug to report against gnome-software or flatpak.

**Comment by antistress** [comment]
I've reported the bug against gnome-software here https://gitlab.gnome.org/GNOME/gnome-software/issues/705

Thanks.
