### ISSUE TITLE
Icon is missing in audacity Flatpak with GNOME-X11

### ISSUE THREAD

**Issue by antistress** [flathub/org.audacityteam.Audacity#34]
Hi,
Icon of the pointer over the track is missing in audacity flatpak.
Icon of the pointer while resizing over the track is OK.
I've attached 2 screenshots : the first is ok (with audacity deb) the second shows the bug (with audacity flatpak).
i'm using Debian Sid 64 bits with GNOME-X11
Thanks
![1 OK with distribution deb package](https://user-images.githubusercontent.com/2436957/59206866-239f8680-8ba6-11e9-9c40-f1965b53a262.png)
![2 Pointer icon missing with audacity flatpak](https://user-images.githubusercontent.com/2436957/59206867-239f8680-8ba6-11e9-8859-e3b9c2b029fb.png)

**Comment by jon-breysse** [comment]
Hi,

The same with me (Debian 10 with xorg).

**Comment by antistress** [comment]
Just to be clear : with that bug, Audacity is totally unusable for editing, it can only serve for transcoding.
Therefore this is a major bug to me.
Thanks

**Comment by go-ten** [comment]
Have you tried with a standard theme (Adwaita) ?

**Comment by antistress** [comment]
I have Debian default theme (and don't know how to change it)

**Comment by eszlari** [comment]
Works for me on Kubuntu 19.04 / KDE 5.15.4 / Xorg.

**Comment by go-ten** [comment]
Hello,
For more information, I tried on a Wayland session: no problem.

**Comment by antistress** [comment]
> Hello,
> For more information, I tried on a Wayland session: no problem.

Interesting : there's indeed no problem on a Wayland session.
Problem only occurs on a X11 session
Thanks for pointing this

**Comment by go-ten** [comment]
J'ai vu ton blog, je n'avais pas vu que tu parlais français :-)
Je suis également en train de passer sur du full flatpak. J'ai le même type de problème sur libre Office, quand je veux faire un copier coller de mise en forme (reproduire la mise en forme).

Pour info, ces problèmes n'appaissent pas avec des paquets Snap.

A+

**Comment by dlalinsp** [comment]
I am a bit late but I can confirm that this bug is still there in Audacity 2.4.1. I am using Linux Mint 19.3. 
![Screenshot from 2020-06-02 04-46-00](https://user-images.githubusercontent.com/34846387/83463584-1735cd00-a48c-11ea-870d-631b497a00d5.png)

**Comment by Unrud** [comment]
I confirmed with **strace** that **audacity** opens the cursor icons from `/run/host/share/icons/THEME/cursors/...`. But they are displayed completely jumbled.

**Workaround:** Switching the runtime to Gnome fixes the problem although I don't know why:

```
flatpak run --runtime=org.gnome.Platform//3.36 org.audacityteam.Audacity
```

**Comment by Unrud** [comment]
**Audacity** creates custom cursors from [wxImage](https://docs.wxwidgets.org/trunk/classwx_image.html) with [wxCursor](https://docs.wxwidgets.org/trunk/classwx_cursor.html#adaf6e394c7306a3999bdc314d7b307a7). Internally this uses [gdk-cursor-new-from-pixbuf](https://developer.gnome.org/gdk3/stable/gdk3-Cursors.html#gdk-cursor-new-from-pixbuf).
For some reason the cursors are displayed jumbled (e.g. transparent and non-transparent pixels are switched, black and white pixels are switched...).

I created a small test program that shows a window with a custom cursor:

```c++
#include <wx/wxprec.h>
#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif
class TestApp: public wxApp
{
public:
    virtual bool OnInit();
};
class TestFrame: public wxFrame
{
public:
    TestFrame(const wxString& title, const wxPoint& pos, const wxSize& size);
};
wxIMPLEMENT_APP(TestApp);
bool TestApp::OnInit()
{
    TestFrame *frame = new TestFrame("Test App", wxPoint(50, 50), wxSize(450, 340));
    frame->Show(true);
    return true;
}
TestFrame::TestFrame(const wxString& title, const wxPoint& pos, const wxSize& size)
        : wxFrame(NULL, wxID_ANY, title, pos, size)
{
    static unsigned char down_bits[] = { 255, 255, 255, 255, 31,
        255, 255, 255, 31, 255, 255, 255, 31, 255, 255, 255,
        31, 255, 255, 255, 31, 255, 255, 255, 31, 255, 255,
        255, 31, 255, 255, 255, 31, 255, 255, 255, 25, 243,
        255, 255, 19, 249, 255, 255, 7, 252, 255, 255, 15, 254,
        255, 255, 31, 255, 255, 255, 191, 255, 255, 255, 255,
        255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
        255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
        255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
        255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
        255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
        255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
        255 };
    static unsigned char down_mask[] = { 240, 1, 0, 0, 240, 1,
        0, 0, 240, 1, 0, 0, 240, 1, 0, 0, 240, 1, 0, 0, 240, 1,
        0, 0, 240, 1, 0, 0, 240, 1, 0, 0, 255, 31, 0, 0, 255,
        31, 0, 0, 254, 15, 0, 0, 252, 7, 0, 0, 248, 3, 0, 0,
        240, 1, 0, 0, 224, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0 };
    wxCursor down_cursor = wxCursor((char*)down_bits, 32, 32, 6, 14,
                                    (char*)down_mask, wxBLACK, wxWHITE);
    SetCursor(down_cursor);
}
```
Compile with ``g++ $(wx-config --cxxflags --libs) TestApp.cpp -o wx-test``

**Comment by Unrud** [comment]
I tracked down the problem to **libgdk-3.so.0**. Building **GTK+3** from source fixes the problem, even if it's the same version as shipped by the ``org.freedesktop.Platform`` runtime.
Using the version of **libgdk-3.so.0** from ``org.gnome.Platform//3.36`` with ``$LD_PRELOAD_PATH`` also works.
This doesn't make any sense to me.

**Comment by CHJ85** [comment]
Is there a fix to this bug yet.
Because until this bug has been fixed, I'm stuck with the 2.3.3 version.
Is there perhaps a way I can let audacity use the systemwide mouse cursor theme?

**Comment by Unrud** [comment]
> Is there a fix to this bug yet.

Have you tried ``flatpak run --runtime=org.gnome.Platform//3.36 org.audacityteam.Audacity`` ?

**Comment by CHJ85** [comment]
@Unrud Holy shit, that worked.
Thank you so much.

**Comment by CHJ85** [comment]
@Unrud actually nevermind.
It worked the first time. But thanks anyway.
I found another bug as well. My VST plugins are gone.
So I figured I might as well switch back to the APT version where everything works.

**Comment by Unrud** [comment]
> It worked the first time. But thanks anyway.

You have to start it with the command every time.

> I found another bug as well. My VST plugins are gone.

Yes, it's only a hack to test it. The Flatpak must be rebuild with the Gnome runtime to make it permanent.

**Comment by CHJ85** [comment]
@Unrud I did. Even added it to the start menu launcher.

**Comment by Unrud** [comment]
> @Unrud I did. Even added it to the start menu launcher.

That's unfortunate, it's a tricky bug.

**Comment by jonpatterns** [comment]
Audacity and the WxWidgets it uses should be built against gtk2 not gtk3. I don't know if this could be a source of this bug.

https://wiki.audacityteam.org/wiki/Building_On_Linux

**Comment by hfiguiere** [comment]
> Audacity and the WxWidgets it uses should be built against gtk2 not gtk3. I don't know if this could be a source of this bug.
> 
> https://wiki.audacityteam.org/wiki/Building_On_Linux

This would mean Audacity wouldn't work on HiDPI displays.
