### ISSUE TITLE
Maintainership

### ISSUE THREAD

**Issue by jurf** [flathub/org.audacityteam.Audacity#37]
I’ve received enough pings on IRC to know that at least several people consider me the maintainer of Audacity on Flathub. However, I simply do not have the time/resources/use case/know-how for that role. Maintaining just the apps I submitted to Flathub has gotten out of hand and started eating more of my time than I am happy to provide.

@flathub/admins – I, therefore, ask for my write access to this repo to be revoked.

Cheers.

**Comment by TingPing** [comment]
Done.
