### ISSUE TITLE
Can org.audacityteam.Audacity be launched as a native wayland application ?

### ISSUE THREAD

**Issue by antistress** [flathub/org.audacityteam.Audacity#44]
Hi,

I've just checked on my Debian Testing GNOME-Wayland system with $ xlsclients and org.audacityteam.Audacity is running through XWayland.

Can org.audacityteam.Audacity be used without XWayland (for instance using --socket=wayland or any other setting), as a native wayland application ?

Here is what I found :
https://bugzilla.redhat.com/show_bug.cgi?id=1303417

Thanks !

**Comment by TingPing** [comment]
You can test it yourself, IME WXWidgets doesn't like it.

**Comment by antistress** [comment]
Ok, I'm testing it at present time. Seems OK for the moment.
I will report here after a few days.
Thanks

**Comment by antistress** [comment]
Ok, during past 10 days, using org.audacityteam.Audacity in its Wayland flavor, for very basics tasks (cut & export), I couldn't find any bug.
BTW, note that I had to rewrite /var/lib/flatpak/exports/share/applications/org.audacityteam.Audacity.desktop several times : I guess that '--socket=wayland' parameter is erased in case of an update ? 
Thanks

**Comment by eszlari** [comment]
> BTW, note that I had to rewrite /var/lib/flatpak/exports/share/applications/org.audacityteam.Audacity.desktop several times : I guess that '--socket=wayland' parameter is erased in case of an update ?

Yes, but I have merged the fix, so this isn't needed anymore.

**Comment by antistress** [comment]
Thanks !
