### ISSUE TITLE
Bundled plugins are missing

### ISSUE THREAD

**Issue by neildarlow** [flathub/org.audacityteam.Audacity#50]
With the advent of Audacity-2.4.0 all packaging of Audacity appear to be excluding the bundled Nyquist plugins.

The list of enabled plugin types doesn't show Nyquist anymore and the /usr/share/audacity/plug-ins directory (if that's the correct name/case) is absent.

This might be caused by a change to the build process since 2.4.0 but it requires modification of packaging to produce a working application.

**Comment by eszlari** [comment]
Are sure, you are running the flatpak version?

![audacity_build_info](https://user-images.githubusercontent.com/15569934/82754873-2ce22d00-9dd0-11ea-9d1a-efc01a6badd5.png)

> The list of enabled plugin types doesn't show Nyquist anymore and the /usr/share/audacity/plug-ins directory (if that's the correct name/case) is absent.

```
$ flatpak run --command=sh org.audacityteam.Audacity
[📦 org.audacityteam.Audacity ~]$ ls /app/share/audacity/nyquist/
aud-do-support.lsp  dspprims.lsp  envelopes.lsp  equalizer.lsp  evalenv.lsp  fileio.lsp  init.lsp  misc.lsp  nyinit-dbg.lsp  nyinit.lsp  nyqmisc.lsp  nyquist-plot.txt
```

**Comment by neildarlow** [comment]
Hi,
Yes, I am. If you look in e.g. audacity-minsrc-2.4.1.tar.xz there is a folder **plug-ins** with the following content which doesn't get included in the Flatpak. These are effects which you won't find listed under the Effects menu:
adjustable-fade.ny
beat.ny
clipfix.ny
crossfadeclips.ny
crossfadetracks.ny
delay.ny
equalabel.ny
eq-xml-to-txt-converter.ny
highpass.ny
limiter.ny
lowpass.ny
noisegate.ny
notch.ny
nyquist-plug-in-installer.ny
pluck.ny
rhythmtrack.ny
rissetdrum.ny
rms.ny
sample-data-export.ny
sample-data-import.ny
SilenceMarker.ny
SoundFinder.ny
spectral-delete.ny
SpectralEditMulti.ny
SpectralEditParametricEQ.ny
SpectralEditShelves.ny
StudioFadeOut.ny
tremolo.ny
vocalrediso.ny
vocoder.ny

Also, the list .lsp files in the nyquist folder previously listed is incomplete. The source archive contains:
aud-do-support.lsp
dspprims.lsp
envelopes.lsp
equalizer.lsp
evalenv.lsp
fileio.lsp
init.lsp
misc.lsp
nyinit-dbg.lsp
nyinit.lsp
nyqmisc.lsp
nyquist.lsp
printrec.lsp
profile.lsp
sal.lsp
sal-parse.lsp
seqfnint.lsp
seq.lsp
seqmidi.lsp
sliders.lsp
sndfnint.lsp
spec-plot.lsp
spectral-analysis.lsp
stk.lsp
system.lsp
test.lsp
velocity.lsp
xlinit.lsp
xm.lsp

This results in Nyquist not being listed in **Preferences|Effects** with the other effect types:
![preferences-effects](https://user-images.githubusercontent.com/6245505/82757608-73885500-9dd9-11ea-90cd-1e43dc3b96b5.png)

**Comment by neildarlow** [comment]
As confirmation I'm using the Flatpak:
neil@satellite:~$ flatpak info org.audacityteam.Audacity
Ref: app/org.audacityteam.Audacity/x86_64/stable
ID: org.audacityteam.Audacity
Arch: x86_64
Branch: stable
Origin: flathub
Collection ID: org.flathub.Stable
Date: 2020-05-21 11:13:21 +0000
Subject: audacity 2.4.1 (b18ad8b9)
Commit: 649bacef62f41c8f7fa2ccf361aa274a2d06612119cf18e4cdbcaaa54e1cbf07
Parent: 535a9fb206b373fbad3326442c79e0964d3491b7d11e438cd099f3b13bbc267f
Location: /var/lib/flatpak/app/org.audacityteam.Audacity/x86_64/stable/649bacef62f41c8f7fa2ccf361aa274a2d06612119cf18e4cdbcaaa54e1cbf07
Installed size: 84.5 MB
Runtime: org.freedesktop.Platform/x86_64/19.08
Sdk: org.freedesktop.Sdk/x86_64/19.08
neil@satellite:~$ dpkg -l |grep -i audacity

**Comment by eszlari** [comment]
Apparently, the autotools-based build is deprecated now, switching to cmake fixed it.
