### ISSUE TITLE
Use wxWidgets 3.1.3

### ISSUE THREAD

**Issue by nahuelwexd** [flathub/org.audacityteam.Audacity#52]
The Audacity team seems to recommend using wxWidgets 3.1.3 in order to solve several of the errors that used to be found in the app https://www.audacityteam.org/audacity-2-4-2-released/

I have noticed the comment in the manifest about the HiDPI being broken in the v3.1. I currently lack the resources to test this, but someone who can should should do so to ensure that Audacity runs as expected (and avoid possible error reports to the upstream where the failure is in the packaging)

**Comment by eszlari** [comment]
> I have noticed the comment in the manifest about the HiDPI being broken in the v3.1. I currently lack the resources to test this, but someone who can should should do so

Of course, I did test it, that's why I added that comment.

**Comment by neildarlow** [comment]
Hi,
May I also add that the Audacity Team used a version of wxWidgets 3.1.x with additional patches of their own. It isn't a vanilla version.

ATB,
Neil Darlow

**Comment by Unrud** [comment]
> I have noticed the comment in the manifest about the HiDPI being broken in the v3.1. I currently lack the resources to test this, but someone who can should should do so to ensure that Audacity runs as expected (and avoid possible error reports to the upstream where the failure is in the packaging)

Test result: HiDPI is still broken with version 3.1.4.

> May I also add that the Audacity Team used a version of wxWidgets 3.1.x with additional patches of their own. It isn't a vanilla version.

HiDPI is broken with that version too. (https://github.com/audacity/wxWidgets/commit/84e3f51eff521931b1f25db30d52b99af20f6f88)

All builds were using GTK3, because HiDPI doesn't work with GTK2 anyway (it only scales font sizes).

**Comment by jonpatterns** [comment]
But not building against Gtk2 seems to break other things.

https://wiki.audacityteam.org/wiki/Building_On_Linux
