### ISSUE TITLE
Failed to load module "canberra-gtk-module"

### ISSUE THREAD

**Issue by therealkitman** [flathub/org.audacityteam.Audacity#58]
Hi, I have installed Flatpak for the first time under openSUSE 15.2 with LXDE. Wanted to try out Audacity but I get this error -

```
chris@asus-roc:~>` flatpak run org.audacityteam.Audacity
Gtk-Message: 17:36:01.653: Failed to load module "canberra-gtk-module"
No protocol specified
Unable to init server: Could not connect: Connection refused
17:36:01: Error: Unable to initialize GTK+, is DISPLAY set properly?
```

This is my only application installed.

```
chris@asus-roc:~> flatpak list
Name                                               Application ID                                       Version            Branch            Installation
Audacity                                           org.audacityteam.Audacity                            2.4.2              stable            system
Codecs                                             org.audacityteam.Audacity.Codecs                                        stable            system
default                                            org.freedesktop.Platform.GL.default                                     20.08             system
nvidia-460-39                                      org.freedesktop.Platform.GL.nvidia-460-39                               1.4               system
openh264                                           org.freedesktop.Platform.openh264                    2.1.0              2.0               system
GNOME Application Platform version 3.38            org.gnome.Platform                                                      3.38              system
chris@asus-roc:~> 
```
Do I need to install something from my OS's repo?

Thanks.

**Comment by eszlari** [comment]
The message `Failed to load module "canberra-gtk-module"` is harmless and can be ignored.

From googling, the message `Unable to initialize GTK+, is DISPLAY set properly?` could mean that you are running as root, which you should not do: https://bbs.archlinux.org/viewtopic.php?id=133667

**Comment by therealkitman** [comment]
> could mean that you are running as root,

I am not running as root.

**Comment by therealkitman** [comment]
Ok, Just installed Gimp program and I get the same problem.

```
chris@asus-roc:~> flatpak run org.gimp.GIMP
Gtk-Message: 09:04:09.543: Failed to load module "canberra-gtk-module"
No protocol specified
Cannot open display: 
chris@asus-roc:~>
```
Obviously I am not understanding something about Flatpak in general here but damned if I know what.

**Comment by therealkitman** [comment]
Well this is whacky!
I built a VM with opensuse with LXDE, Gnome and KDE Plasma. Installed audacity and kdenlive flatpaks.

Both apps ONLY work in a Gnome desktop and fail in LXDE and KDE. 

Obviously not an issue for this repo but can anyone steer me in a direction for further reference. I'll be damned using a Gnome DE.
Thanks.

**Comment by eszlari** [comment]
Have you installed `xdg-desktop-portal-kde`?

**Comment by therealkitman** [comment]
> Have you installed `xdg-desktop-portal-kde`

Thanks for the reply.

No I have not installed that. That would mean installing over 200 extra KDE/Qt packages only my LXDE only system.

I'm getting the impression that Flatpaks do not provide all required libraries etc and that some manual adding of extra DE packages is required.

**Comment by eszlari** [comment]
You could also try `xdg-desktop-portal-gtk`.

**Comment by therealkitman** [comment]
> You could also try `xdg-desktop-portal-gtk`

That is already installed.

**Comment by therealkitman** [comment]
Had a reply on another forum - I would have to install a KDE or Gnome DE. So Flatpaks are not DE agnostic as I'm staying with LXDE.

On to other experiments.

Thanks.

**Comment by eszlari** [comment]
There is also `xdg-desktop-portal-wlr` if you use a `wlroots` based Wayland compositor like Sway: https://swaywm.org

So Flatpak is DE agnostic, it's just that you chose a DE that lacks the manpower write its own implementation.
