### ISSUE TITLE
will you switch to  temporary-audacity/audacity after the new audacity drama

### ISSUE THREAD

**Issue by teh404guy** [flathub/org.audacityteam.Audacity#72]
since audacity started collecting HWIDs and IP addresses, a new fork of audacity was made to remove the spyware
im asking if you are planing on rebasing this project to temporary-audacity/audacity

**Comment by hfiguiere** [comment]
no.

but the "networking" is already disabled on the 3.0.3-rc test.

**Comment by hfiguiere** [comment]
it's PR #71 I'm talking about.

**Comment by mb291** [comment]
> no.
> 
> but the "networking" is already disabled on the 3.0.3-rc test.

So this means the flatpak won' t get updatecheck and crash reports ? Which is a good decision imo.
