### ISSUE TITLE
App version internal isn't marked as release

### ISSUE THREAD

**Issue by RDKRACZ** [flathub/org.audacityteam.Audacity#75]
I installed stable flatpak only to find out it's an alpha release:
![Screenshot from 2021-08-26 14-36-27](https://user-images.githubusercontent.com/43277609/130963726-ecacf728-94b0-4b39-b29f-d732843f88ad.png)
![Screenshot from 2021-08-26 14-36-08](https://user-images.githubusercontent.com/43277609/130963729-02adeb84-524f-4856-8d7d-dd3413cc4ff9.png)
![Screenshot from 2021-08-26 14-35-59](https://user-images.githubusercontent.com/43277609/130963732-acb0d755-e44a-4835-902a-d67f8c9e45b2.png)

**Comment by hfiguiere** [comment]
Should be fixed in the next build.
