### ISSUE TITLE
Playback is silent/no sound

### ISSUE THREAD

**Issue by ell1e** [flathub/org.audacityteam.Audacity#77]
I'm on Fedora 34 with Flatpak 1.10.2, and with the latest x64 flatpak of Audacity 3.0.2 any attempt to play an open project will visually indicate it playing (with colored volume meters flashing and the playback marker progressing) but won't actually produce any sound. It's just dead silent. If you need any logs, let me know which ones/where they are and I'd be happy to help out.

**Comment by hfiguiere** [comment]
Install 3.0.4 (`flatpak update`). it should have better sound support, including by using jack.

**Comment by ell1e** [comment]
It doesn't offer that update to me for some reason, the latest I get is `3.0.2`.

**Comment by hfiguiere** [comment]
not sure why it doesn't update.

works fine here on Fedora 34.

**Comment by hfiguiere** [comment]
Is it still a problem with 3.1?

**Comment by hfiguiere** [comment]
Reopen if you still have a problem.

**Comment by ell1e** [comment]
The flatpak is still stuck at `3.0.2` for me, so nothing has changed. The native package by Fedora also doesn't have sound either, though.

**Comment by hfiguiere** [comment]
not sure what's happening with your flatpak here, but 3.1.1 is the latest available.

**Comment by hfiguiere** [comment]
this is the problem that should be addressed first. why it is not updating.

**Comment by ell1e** [comment]
Okay I'm just not smart enough to use flatpak :woman_facepalming: turns out I had it installed from some special fedora flatpak repo (which I didn't even know existed, and somehow GNOME Software just quietly defaulted to) instead of from flathub which I *thought* I had. And the flatpak version now has pulseaudio output as an option, and it works, and it's 3.1.1, and everything is good. My apologies for the confusion!

**Comment by JayDoubleu** [comment]
@ell1e you can raise bugs for fedora rpm/flatpak software here https://src.fedoraproject.org/rpms/audacity
