### ISSUE TITLE
Flatpak fails to launch

### ISSUE THREAD

**Issue by notklaatu** [flathub/org.audacityteam.Audacity#84]
OS:

```
NAME="CentOS Stream"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Stream 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"
```

Flatpak version:

```
$ flatpak --version
Flatpak 1.8.5
```

Error:

```
$ flatpak run org.audacityteam.Audacity
(process:2): Gdk-CRITICAL **: 22:21:29.267: gdk_screen_get_root_window: assertion 'GDK_IS_SCREEN (screen)' failed
(process:2): Gdk-CRITICAL **: 22:21:29.267: gdk_window_get_display: assertion 'GDK_IS_WINDOW (window)' failed
(process:2): Gdk-CRITICAL **: 22:21:29.267: gdk_cursor_new_from_pixbuf: assertion 'GDK_IS_DISPLAY (display)' failed
```

Expected result:  Audacity should launch. Other Flatpaks (Signal, Kdenlive, Inkscape) launch as usual.

**Comment by hfiguiere** [comment]
these messages are a red hearing.

they happen no matter what.

do you have pipewire by any chance? if yes which version?

**Comment by wsdfhjxc** [comment]
After switching from PulseAudio to PipeWire (libpipewire 0.3.32), I also can't run Audacity.

**Comment by notklaatu** [comment]
```
$ pipewire --version
pipewire
Compiled with libpipewire 0.3.6
Linked with libpipewire 0.3.6
```

**Comment by wsdfhjxc** [comment]
It turns out, after upgrading libpipewire to version 0.3.40, Audacity started working again.

**Comment by vchernin** [comment]
The PipeWire version in the runtime is probably newer than the one on the host, [which can cause problems](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/1515). But hopefully this will be better going forward.
