### ISSUE TITLE
wrong button size and other glitches

### ISSUE THREAD

**Issue by christian-rauch** [flathub/org.audacityteam.Audacity#85]
I am using Audacity on a HiDPI screen and the buttons are wrongly scaled and the time mark (at green triangle) shows glitches:
![Screenshot from 2021-12-06 20-19-36](https://user-images.githubusercontent.com/8226248/144916545-d0979a83-06ad-4ca9-abcf-0854956c0913.png)

Other parts of the UI are correct, but most buttons are only shown with the top left quarter.

I suspect that `wxwidgets` is causing this. Is there a reason why the fork at https://github.com/audacity/wxWidgets.git is used and not the official upstream at https://github.com/wxWidgets/wxWidgets.git?

**Comment by christian-rauch** [comment]
The PR https://github.com/flathub/org.audacityteam.Audacity/pull/86 fixes the button scaling issue:
![Screenshot from 2021-12-07 12-42-36](https://user-images.githubusercontent.com/8226248/145031236-489d0f38-d117-4fb3-949c-881828302203.png)

But the glitches remain.

**Comment by hfiguiere** [comment]
"Why the fork" is question for upstream. We use the fork because that's what they recommend. But I doubt they care about HiDPI since they still recommend to build it with Gtk2 which we don't.

Using upstream might break other thing as I have no idea if the patches from the fork have been submitted.

**Comment by christian-rauch** [comment]
The now deprecated build instructions https://wiki.audacityteam.org/wiki/Building_On_Linux#Instructions state:
> Audacity's fork of wxWidgets 3.1.3 (https://github.com/audacity/wxWidgets) should
be used as this includes bug fixes that are not yet available upstream.
WxWidgets should be built with gtk2 as gtk3 is not yet fully supported.

According to these old instructions, one should use their wxWidgets fork together with gtk2

However, the new instructions at https://github.com/audacity/audacity/blob/master/BUILDING.md do not say anything about using their fork or gtk2. So I think it's safe to use gtk3 and the upstream wxWidgets.
