### ISSUE TITLE
Audacity 3.1.3 installs but will not run

### ISSUE THREAD

**Issue by TMPinSYR** [flathub/org.audacityteam.Audacity#90]
First time posting here. My apologies if I miss something. Please let me know what other information I can share to assist.

Linux beginner here. I'm running Pop!_OS 21.10. I had Audacity installed via the Pop!_Shop and had been using ver 3.x.x for months. The latest update via flatpak in the Shop is version 3.1.3. After updating to 3.1.3, Audacity does not appear to run. It would create a small blank black box in the screen as if it was starting but would not actually open.

I tried uninstalling and reinstalling, nothing. Eventually I used the Synaptic Package Manager to install version 2.4.2~dfsg0-5. (I had to record a podcast episode tonight.) The older version ran normally. I'd like to get back to the 3.x.x version.

After we recorded, I kept digging and found that Audacity has released an AppImage file for the newest version. I downloaded that, made the file runnable and was able to start 3.1.3 with no issue. At this point I suspect there is an issue with the flatpak build.

**Comment by hfiguiere** [comment]
or an issue with PopOS

**Comment by TMPinSYR** [comment]
Yes but version 3.1.3 run from the AppImage with no problem. Is there anything I can provide to help diagnose where the issue might be? (Not arguing - genuinely trying to be useful here.)

**Comment by joshontech** [comment]
![Screenshot_20220112_102747](https://user-images.githubusercontent.com/44295541/149170466-c292eb40-7e05-4ae4-bf0a-56063b4157d3.png)

This is the error message I am getting from the Audacity Flatpak. When launching from the GUI menu nothing happens and when I launch it from terminal this error is what I get.

I am running Feren OS with the kde desktop based on Ubuntu 20.04. I tried both the 5.11 kernel and 5.13 Ubuntu stock kernel and also the Xanmod 5.15.14 kernel all have the above issue.

GTK Versions installed.
ii  libgtk-3-0:amd64             3.24.20-0ubuntu1   amd64        GTK graphical user interface library
ii  libgtk2.0-0:amd64            2.24.32-4ubuntu4   amd64        GTK graphical user interface library - old version

**Comment by Dale-CDL** [comment]
I am using Pop!_OS 21.10 with Kernel 5.15.11 and Gnome 40.5.  It is using X11, not Wayland.
There is a problem with the Flatpak also.  I will include the terminal output.  When I try to launch it from the desktop, all I get is a postage stamp size square on my screen.  That will eventually go away.  When I launch it from the terminal, I get a lot of errors.

dale@odin:~$ flatpak run org.audacityteam.Audacity

(process:2): Gdk-CRITICAL **: 08:26:04.220: gdk_screen_get_root_window: assertion 'GDK_IS_SCREEN (screen)' failed

(process:2): Gdk-CRITICAL **: 08:26:04.220: gdk_window_get_display: assertion 'GDK_IS_WINDOW (window)' failed

(process:2): Gdk-CRITICAL **: 08:26:04.220: gdk_cursor_new_from_pixbuf: assertion 'GDK_IS_DISPLAY (display)' failed
dale@odin:~$ flatpak remove org.audacityteam.Audacity

**Comment by taunoe** [comment]
I have the same problem as described - on Pop Os.

**Comment by dirkk0** [comment]
me too, also with Muse.

**Comment by Dale-CDL** [comment]
I installed Debian Testing on my desktop and the flatpak of Audacity works.  I tried it again on my laptop running Pop!_OS and it will still not run.

**Comment by waiting-for-signs** [comment]
I can confirm that this problem exists under POP!-OS 21.10 (wayland), Gnome 40.5.
The small square audacity logo pops up, goes black and thats that. Audacity runs as process, but you cant use it...

**Comment by christianrauch** [comment]
Same problem and assertion messages on Ubuntu 20.04.

The snap package of the same version works without issues.

**Comment by SimoneStarace** [comment]
I'm using:

- OS: Pop!_OS 22.04 LTS x86_64
- Kernel: 5.17.5-76051705-generic

I had the same error message of @joshontech and I even tried to use the AppImage available on the website but nothing.
I don't know if this is the problem  of Pop_OS or the software Audacity but to solve the problem I have installed the one present in the repository but it's an old version.

**Comment by dirkk0** [comment]
I am also on POP!_OS 22.04 LTS and the AppImage is running fine for me.
You only need to set the execute bit, but from there on Audacity runs flawless.
The flatpak version doesn't work.

**Comment by TMPinSYR** [comment]
Interesting... I've since upgraded to POP!_OS 22.04 LTS and now the AppImage for 3.1.3 will not run. The opening logo appears but just sits there. I eventually get a "Audacity" is not responding box.

**Comment by christianrauch** [comment]
I am sure this is not the right place to report issues with the AppImage version.

**Comment by TMPinSYR** [comment]
> I am sure this is not the right place to report issues with the AppImage version.

Ah - good point. Thanks!

**Comment by hfiguiere** [comment]
All I see is that Ubuntu based distro fail. I'm tempted to say there is a problem with Ubuntu based distro. 

If someone can figure out...

**Comment by ovari** [comment]
Audacity (flatpak) hangs when opened with Linux Mint 21.
https://github.com/linuxmint/mint21-beta/issues/38

Ubuntu has pipewire version 0.3.48.

Does Audacity flatpak work with pipewire version 0.3.48? If not, can Audacity please work with pipewire version 0.3.48?

Thank you

**Comment by SimoneStarace** [comment]
I have re-installed Audacity using flatpak and now seems to work again.
Should this issue being closed now?

**Comment by ovari** [comment]
> I have re-installed Audacity using flatpak and now seems to work again.

Does it work with Linux Mint 21 Cinnamon?
https://blog.linuxmint.com/?p=4358

Thank you

**Comment by TMPinSYR** [comment]
FWIW, the Flatpak version is working for me now as well. (I don't know who makes the decision on closing the issue.)

**Comment by LWinterberg** [comment]
There are some reports here saying it doesn't work on Linux Mint 21 in the flatpak version either: 

* https://github.com/audacity/audacity/issues/3332
* https://forums.linuxmint.com/viewtopic.php?t=377877
