### ISSUE TITLE
Missing developer/project/organisation name mention

### ISSUE THREAD

**Issue by Ricky-Tigg** [flathub/org.audacityteam.Audacity#92]
Hello. The worth mentioning developer/project/organisation name is missing from this application [metadata](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-developer_name) file – usually XML. As a result it is
- not exhibited at https://flathub.org/apps/. 
- reported as "Unknown" by Flatseal

![Flatpak_Flatseal_Audacity](https://user-images.githubusercontent.com/26058215/160832742-1bb095cf-bbc8-4413-95a9-733fa4ab18ca.png)

**Steps to reproduce the behavior:**
1. Install Flatpak applications github.tchx84.Flatseal and org.audacityteam.Audacity
2. Start Flatseal | '`flatpak run com.github.tchx84.Flatseal`'
3. Select _Audacity_. Inspect headers.

**Action required for fixing:** |  lasts at most two minutes so the ticket could be closed yet today.

Addition of  `<developer_name>Muse Group</developer_name>` into that model of XML
```xml
<?xml version="1.0" encoding="utf-8"?>
<component type="desktop">
 ...
</component>
```

**Comment by hfiguiere** [comment]
the appdata file comes from upstream, so it is their responsibility. Also this flatpak isn't supported by them anyway.

**Comment by Ricky-Tigg** [comment]
That precisely a comment from **them** that convinced me to report here. Unknown remains the maintainer of that XML file.

**Comment by hfiguiere** [comment]
This is the file we use:
https://github.com/audacity/audacity/blob/Audacity-3.1.3/help/audacity.appdata.xml

Except that  1. it's renamed and installed in the right location 2. we have to add a mandatory release tag to display the version. 

So, I'll say it one more time, it's not an issue with the packaging but with what upstream provides.
